#ifndef BINDS_H
#define BINDS_H

namespace battleship{
	enum Bind{
		LEFT_CLICK, // Bind 0
		SCROLLING_UP, // 1
		SCROLLING_DOWN, // 2
		LEFT, // 3
		RIGHT, // 4
		DELETE_CHAR, // 5
		TOGGLE_MAIN_MENU, // 6
		LOOK_UP, // 7
		LOOK_DOWN, // 8
		LOOK_LEFT, // 9
		LOOK_RIGHT, // 10
		LOOK_AROUND, // 11
		DRAG_BOX, // 12
		ROTATE_OBJ_FRAME, // 13
		HALT, // 14
		ZOOM_IN, // 15
		ZOOM_OUT, // 16
		LEFT_CONTROL, // 17
		LEFT_SHIFT, // 18
		SELECT_PATROL_POINTS, // 19
		LAUNCH, // 20
		SHIFT_SUB_DEPTH, // 21
		GROUP_0, // 22
		GROUP_1, // 23
		GROUP_2, // 24
		GROUP_3, // 25
		GROUP_4, // 26
		GROUP_5, // 27
		GROUP_6, // 28
		GROUP_7, // 29
		GROUP_8, // 30
		GROUP_9, // 31
		SELECT_STRUCTURE, // 32
		DESELECT_STRUCTURE, // 33
		DECREASE_RADIUS, // 34
		INCREASE_RADIUS, // 35
		PUSH_VERTS_UP, // 36
		PUSH_VERTS_DOWN, // 37
		MOVE_TERR_OBJ, // 38
		SCALE_TERR_OBJ, // 39
		STOP_TERR_OBJ, // 40
		ENABLE_X_AXIS, // 41
		ENABLE_Y_AXIS, // 42
		ENABLE_Z_AXIS, // 43
		CREATE_WATERBODY, // 44
		GENERATE_WEIGHTS, // 45
		TOGGLE_CELL_MARKERS, // 46
		EJECT_GARRISON, // 47
		ENABLE_CHASE_STATE, // 48
		ENABLE_STAND_GROUND_STATE, // 49
		ENABLE_HOLD_FIRE_STATE, // 50
		HACK, // 51
		MOVE_CAMERA, // 52
		Key_Q // 53
	};
}

#endif
