mappings = {
		{bind = 0, trigger = 0, action = true, bindType = 1, inOptions = false},
		{bind = 1, trigger = 87, action = true, bindType = 0, inOptions = false},
		{bind = 2, trigger = 83, action = true, bindType = 0, inOptions = false},
		{bind = 3, trigger = 263, action = true, bindType = 0, inOptions = false},
		{bind = 4, trigger = 262, action = true, bindType = 0, inOptions = false},
		{bind = 5, trigger = 259, action = true, bindType = 0, inOptions = false},

		{bind = 6, trigger = 256, action = true, bindType = 0, inOptions = true},

		{bind = 7, trigger = 312, action = false, bindType = 2, inOptions = false},
		{bind = 8, trigger = 313, action = false, bindType = 2, inOptions = false},
		{bind = 9, trigger = 310, action = false, bindType = 2, inOptions = false},
		{bind = 10, trigger = 311, action = false, bindType = 2, inOptions = false},
		{bind = 11, trigger = 2, action = true, bindType = 1, inOptions = false},
		{bind = 12, trigger = 0, action = true, bindType = 1, inOptions = true},
		{bind = 13, trigger = 1, action = true, bindType = 1, inOptions = true},
		{bind = 14, trigger = 72, action = true, bindType = 0, inOptions = true},
		{bind = 15, trigger = 0, action = true, bindType = 0, inOptions = true},
		{bind = 16, trigger = 0, action = true, bindType = 0, inOptions = true},
		{bind = 17, trigger = 341, action = true, bindType = 0, inOptions = true},
		{bind = 18, trigger = 340, action = true, bindType = 0, inOptions = true},
		{bind = 19, trigger = 80, action = true, bindType = 0, inOptions = true},
		{bind = 20, trigger = 76, action = true, bindType = 0, inOptions = true},
		{bind = 21, trigger = 32, action = true, bindType = 0, inOptions = true},
		{bind = 22, trigger = 48, action = true, bindType = 0, inOptions = true},
		{bind = 23, trigger = 49, action = true, bindType = 0, inOptions = true},
		{bind = 24, trigger = 50, action = true, bindType = 0, inOptions = true},
		{bind = 25, trigger = 51, action = true, bindType = 0, inOptions = true},
		{bind = 26, trigger = 52, action = true, bindType = 0, inOptions = true},
		{bind = 27, trigger = 53, action = true, bindType = 0, inOptions = true},
		{bind = 28, trigger = 54, action = true, bindType = 0, inOptions = true},
		{bind = 29, trigger = 55, action = true, bindType = 0, inOptions = true},
		{bind = 30, trigger = 56, action = true, bindType = 0, inOptions = true},
		{bind = 31, trigger = 57, action = true, bindType = 0, inOptions = true},
		{bind = 32, trigger = 66, action = true, bindType = 0, inOptions = true},
		{bind = 33, trigger = 256, action = true, bindType = 0, inOptions = true},
		{bind = 47, trigger = 69, action = true, bindType = 0, inOptions = false},
		{bind = 48, trigger = 84, action = true, bindType = 0, inOptions = false},
		{bind = 49, trigger = 89, action = true, bindType = 0, inOptions = false},
		{bind = 50, trigger = 85, action = true, bindType = 0, inOptions = false},
		{bind = 51, trigger = 79, action = true, bindType = 0, inOptions = false},

		{bind = 7, trigger = 312, action = false, bindType = 2, inOptions = false},
		{bind = 8, trigger = 313, action = false, bindType = 2, inOptions = false},
		{bind = 9, trigger = 310, action = false, bindType = 2, inOptions = false},
		{bind = 10, trigger = 311, action = false, bindType = 2, inOptions = false},
		{bind = 11, trigger = 1, action = true, bindType = 1, inOptions = false},
		{bind = 33, trigger = 256, action = true, bindType = 0, inOptions = false},
		{bind = 0, trigger = 0, action = true, bindType = 1, inOptions = false},
		{bind = 34, trigger = 67, action = true, bindType = 0, inOptions = false},
		{bind = 35, trigger = 86, action = true, bindType = 0, inOptions = false},
		{bind = 36, trigger = 312, action = false, bindType = 2, inOptions = false},
		{bind = 37, trigger = 313, action = false, bindType = 2, inOptions = false},
		{bind = 38, trigger = 71, action = true, bindType = 0, inOptions = false},
		{bind = 39, trigger = 83, action = true, bindType = 0, inOptions = false},
		{bind = 40, trigger = 256, action = true, bindType = 0, inOptions = false},
		{bind = 41, trigger = 90, action = true, bindType = 0, inOptions = false},
		{bind = 42, trigger = 89, action = true, bindType = 0, inOptions = false},
		{bind = 43, trigger = 88, action = true, bindType = 0, inOptions = false},
		{bind = 44, trigger = 87, action = true, bindType = 0, inOptions = false},
		{bind = 45, trigger = 72, action = true, bindType = 0, inOptions = false},
		{bind = 46, trigger = 68, action = true, bindType = 0, inOptions = false},
}
graphics = {
	resolution = {x = 1920, y = 1080}
}
audio = {
	sfxVolume = 100,
	musicVolume = 100,
}
